name: 'Nick & the Narcsissists'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080609'
    - '#0000ff'
    - '#0080ff'
    - '#00ffff'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
