name: 'Nick & the Narcsissists'
favicon: null
layout_spectrum: 0.4126677408348769
typography_spectrum: 0.7832248811610043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8645808377768844
  lightness: 0.6566773236263543
  saturation: 0.7043905914761126
  rhythmicContrast: 0.24977900949306786
purpose: []
