name: 'Nick & the Narcsissists'
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#09090b'
    - '#7f7fff'
    - '#56ffff'
    - '#ff0000'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
